# Privileged container (will trigger privileged_check)
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: insecure-container
      image: nginx
      securityContext:
        privileged: true
        runAsNonRoot: false  # will also trigger run_as_non_root_check
      resources: {}  # will trigger resources_limits_check

---

# runAsNonRoot false (deployment)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: another-container
          image: nginx
          securityContext:
            runAsNonRoot: false
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits: {}  # empty limits triggers resources_limits_check

---

# Missing resource limits entirely
apiVersion: v1
kind: Pod
metadata:
  name: limitless-pod
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sleep", "3600"]
      resources: {}

---
apiVersion: v1
kind: Pod
metadata:
  name: host-network-pod
spec:
  hostNetwork: true
  containers:
    - name: netcat
      image: busybox
      command: ["sleep", "3600"]

