name: Kubernetes Security Audit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
      - name: Run audit scanner and save report
        run: |
          python audit.py --dir manifests/ --output markdown > audit_report.md
          echo "### kubernetes Security Audit Report"
          cat audit_report.md


      - name: Fail workflow if high severity issues are found
        run: |
          if grep -q "| High |" audit_report.md; then
            echo "High severity issues found in audit!"
            exit 1
          else
            echo "No High severity issues found."
          fi


      - name: Run Bandit (Python SAST)
        run: |
          echo "### Bandit Report"
          bandit -r . -f markdown -o bandit_report.md || true
          cat bandit_report.md


      - name: Check dependencies for known vulnerabilities
        run: |
          echo "### pip audit Report"
          pip-audit || true
