name: Deploy Audit Report to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Run audit via Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/manifests:/app/manifests \
            amir23156/k8s-audit-tool:latest \
            --dir manifests/ --output markdown > audit_report.md

      - name: Run audit and convert to HTML
        run: |
          python audit.py --dir manifests/ --output markdown > audit_report.md
          pandoc audit_report.md -o index.html --standalone --css=https://cdn.simplecss.org/simple.min.css

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
          force_orphan: true
